### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by iakuraa**
Fixed a typo found in the README.

### CODE REVIEW

**Comment by iakuraa** [comment]
Also if you see this, a special request from me hehe. So like, I use VSCodium, but this extension isn't in there registry. Could you upload it so it can work for VSCodium? Thanks, I really love this theme.

**Comment by marlosirapuan** [comment]
Sure. I'll try to publish in there later! thank you

**Comment by marlosirapuan** [comment]
ready, @Fizzify. I don't know if it's correct, but I sent

image

**Comment by iakuraa** [comment]
Thanks man! :) IDK why I wasn't able to see your response.

**Pull request merged**
